#!/usr/bin/env python3
"""
Generate transition-kb/_dependency-map.generated.mmd from KB item JSON files.

Usage:
    python3 scripts/generate_dependency_map.py
    npm run build  (runs automatically as a pre-build step)
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
ITEMS_DIR = REPO_ROOT / "transition-kb" / "items"
OUTPUT = REPO_ROOT / "transition-kb" / "_dependency-map.generated.mmd"

# Tracks rendered in this order; unknown tracks appended alphabetically after.
TRACK_ORDER = ["legal", "medical", "social", "personal"]

HEADER = """\
%% =============================================================================
%% KB DEPENDENCY MAP — GENERATED FILE
%% Do not edit this file directly. It is overwritten on every build.
%% Edit transition-kb/_dependency-map.mmd (the canonical map) instead.
%%
%% ─────────────────────────────────────────────────────────────────────────────
%% HOW THE THREE-FILE CYCLE WORKS
%% ─────────────────────────────────────────────────────────────────────────────
%%
%%  1. Generator  →  _dependency-map.generated.mmd  (this file)
%%     Reads every transition-kb/items/*.json file and emits all items as
%%     Mermaid nodes, grouped into per-track subgraphs.  Hard dependency edges
%%     come directly from each item's JSON `requires` array.
%%     Runs automatically before every `npm run build`, or manually:
%%         python3 scripts/generate_dependency_map.py
%%
%%  2. Canonical  →  _dependency-map.mmd
%%     The developer's working model.  Bootstrap it once by copying this file,
%%     then edit freely: add soft edges, rearrange nodes, wire standalone items
%%     to the _standalone sentinel (see below).  The generator never overwrites
%%     this file.
%%
%%  3. Validator  →  scripts/validate_dependency_map.py
%%     Compares the JSON source (not this file) against the canonical map and
%%     reports drift in four buckets.  Never fails the build.
%%         npm run validate-deps
%%
%% ─────────────────────────────────────────────────────────────────────────────
%% NOTATION
%% ─────────────────────────────────────────────────────────────────────────────
%%
%%  nodeA --> nodeB
%%      Hard dependency edge.  Encoded in nodeA's JSON `requires` field.
%%      Meaning: nodeA cannot be completed before nodeB.
%%      Both this generated file and the canonical map should agree on every
%%      hard edge.  The validator reports disagreements.
%%
%%  nodeA -.-> nodeB
%%      Soft edge.  Appears in the canonical map only — never in this file.
%%      Meaning: a design-only relationship such as a suggested sequence,
%%      thematic grouping, or intentional-standalone classification (see below).
%%      Soft edges are never enforced by the app and never checked by the
%%      validator for drift — they are yours to add, remove, and annotate freely.
%%
%% ─────────────────────────────────────────────────────────────────────────────
%% SENTINEL NODE: _standalone
%% ─────────────────────────────────────────────────────────────────────────────
%%
%%  An item with no hard edges in either direction is ambiguous: it might be
%%  genuinely standalone (correct), or it might be an orphan (a forgotten edge).
%%
%%  To mark an item as intentionally standalone, add a soft edge from that item
%%  to the _standalone sentinel in the canonical map:
%%      my-item -.-> _standalone
%%
%%  The validator reads the canonical map's soft edges to classify each isolated
%%  item:
%%    - Wired to _standalone  →  "intentional standalone"  (suppressed)
%%    - Not wired             →  "unclassified isolated"   (appears in Bucket 4)
%%
%%  Bucket 4 is the to-do list.  Each entry there needs one of two actions:
%%    a) Add a `requires` relationship in the item's JSON  (add a hard edge), or
%%    b) Wire it to _standalone in the canonical map       (declare it intentional)
%%
%% ─────────────────────────────────────────────────────────────────────────────
%% VALIDATOR REPORT BUCKETS
%% ─────────────────────────────────────────────────────────────────────────────
%%
%%  Bucket 1  Hard edge present in JSON, missing from canonical map.
%%            Action: add the edge to _dependency-map.mmd.
%%
%%  Bucket 2  Hard edge present in canonical map, missing from JSON.
%%            Action: either add `requires` to the item's JSON file, or remove
%%            the stale edge from the canonical map.
%%
%%  Bucket 3  Edge exists in both but direction is reversed.
%%            Action: reconcile JSON and canonical manually.
%%
%%  Bucket 4  Item has no hard edges in either direction and is not wired to
%%            _standalone in the canonical map.
%%            Action: add a dependency edge in JSON, or wire to _standalone.
%%
%% Generated: {timestamp}
%% =============================================================================

"""


def slug_to_node(slug: str) -> str:
    """Convert a KB slug (hyphens) to a valid Mermaid node ID (underscores)."""
    return slug.replace("-", "_")


def load_items() -> dict:
    items = {}
    for path in sorted(ITEMS_DIR.glob("*.json")):
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        items[data["slug"]] = data
    return items


def generate(items: dict) -> str:
    parts = [HEADER.format(
        timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    )]

    parts.append("graph TD\n\n")

    # Sentinel node — floats outside all subgraphs
    parts.append('    _standalone["No dependencies — intentional"]\n\n')

    # Group items by track
    by_track: dict[str, list] = {}
    for slug, item in items.items():
        track = item.get("track", "unknown")
        by_track.setdefault(track, []).append(item)

    # Emit subgraphs in canonical order, then any unrecognised tracks
    extra = sorted(t for t in by_track if t not in TRACK_ORDER)
    for track in TRACK_ORDER + extra:
        track_items = by_track.get(track, [])
        parts.append(f"    subgraph {track}\n")
        if not track_items:
            parts.append("        %% no items yet\n")
        else:
            for item in sorted(track_items, key=lambda x: x["slug"]):
                node = slug_to_node(item["slug"])
                label = item.get("label", item["slug"]).replace('"', "'")
                parts.append(f'        {node}["{label}"]\n')
        parts.append("    end\n\n")

    # Collect hard edges
    edges: list[tuple[str, str]] = []
    warnings: list[str] = []
    for slug in sorted(items):
        for req in items[slug].get("requires", []):
            if req in items:
                edges.append((slug_to_node(slug), slug_to_node(req)))
            else:
                warnings.append(
                    f"    %% WARNING: {slug} requires unknown slug '{req}'\n"
                )

    if warnings:
        parts.append("    %% Unknown slugs referenced in `requires` — fix the JSON\n")
        parts.extend(warnings)
        parts.append("\n")

    if edges:
        parts.append("    %% Hard dependency edges (derived from JSON `requires` fields)\n")
        for src, dst in sorted(edges):
            parts.append(f"    {src} --> {dst}\n")
    else:
        parts.append("    %% No hard edges defined yet\n")

    return "".join(parts)


def main() -> None:
    if not ITEMS_DIR.exists():
        print(
            f"ERROR: {ITEMS_DIR} not found — run from repo root.",
            file=sys.stderr,
        )
        sys.exit(1)

    items = load_items()
    content = generate(items)
    OUTPUT.write_text(content, encoding="utf-8")

    edge_count = sum(len(i.get("requires", [])) for i in items.values())
    print(
        f"[dep-map] Generated {OUTPUT.name}: "
        f"{len(items)} items, {edge_count} hard edges"
    )


if __name__ == "__main__":
    main()
